import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));

const artifactPath = path.join(
  root,
  "artifacts/contracts/ClassroomStaking.sol/ClassroomStaking.json",
);

const artifact = JSON.parse(readFileSync(artifactPath, "utf8"));

const banner = `// AUTO-GENERATED by scripts/export-abi.mjs — do not edit by hand.
// Regenerate with: npm run contracts:export-abi
`;

const out = `${banner}
export const STAKING_ABI = ${JSON.stringify(artifact.abi, null, 2)} as const;

export const ERC20_ABI = [
  "function decimals() view returns (uint8)",
  "function balanceOf(address account) view returns (uint256)",
  "function allowance(address owner, address spender) view returns (uint256)",
  "function approve(address spender, uint256 amount) returns (bool)",
] as const;
`;

const outPath = path.join(root, "src/web3/abi.ts");
writeFileSync(outPath, out);
console.log("Wrote", outPath);
